version: '3'
services: 
    app:
        build: 
            context: ./
        volumes: 
            - .:/go/src/app:rw
        ports: 
            - "8080:8081"
        container_name: my-go-app
    db:
        image: mysql:latest
        ports:
            - 3307:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "db_my_go_app"
            container_name: my_go_app_db
        command:
            - --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ["CMD-SHELL", "echo 'select 1' |mysql -uroot -pdbrootpass --silent"]
            interval: 10s
            timeout: 20s
            retries: 6